var makeupD = [
        {
                image:"https://files.myglamm.com/site-images/800x800/Made-cute-1_1.jpg",
                title:"LIT Liquid Matte Lipstick",
                description:"Moringa Oil Enriched Matte Lipstick",
                image1:"https://www.myglamm.com/images/plus-icon.png",
                shades:"100 SHADES",
                price: "₹ 316",
        },
        {
                image:"https://files.myglamm.com/site-images/800x800/RSEAD-(1).jpg",
                title:"LIT - pH Lip Balm",
                description:"Creamy, Hydrating Formula with a Luminous Effect",
                image1:"https://www.myglamm.com/images/plus-icon.png",
                shades:"5 SHADES",
                price:"₹ 345",
        },
        {
                image:"https://files.myglamm.com/site-images/800x800/FLCMP-(1).jpg",
                title:"K.Play Flavoured Compact",
                description:"Vanilla Flavoured Skin Perfecting Powder Compact",
                image1:" ", 
                shades:" ",
                price:"₹ 645",
        },
        {
                image:"https://files.myglamm.com/site-images/800x800/Risque-(1).jpg",
                title:"Ultimatte Long-Stay Matte LipBalm",
                description:"Hyaluronic Acid-enriched,Moisturising Matte Slim",
                image1:"https://www.myglamm.com/images/plus-icon.png",
                shades:"11 SHADES",
                price:"₹ 699",
        },
        {
                image:"https://files.myglamm.com/site-images/800x800/RRD-(1).jpg",
                title:"MyGlamm Pure Love Sindoor",
                description:"Liquid Matte Sindoor",
                image1:"https://www.myglamm.com/images/plus-icon.png",
                shades:"1 SHADES",
                price:"₹ 175",
        },
        {
                image:"https://files.myglamm.com/site-images/800x800/Wheelie-(1).jpg",
                title:"Precision Eyeliner and Stylist",
                description:" ",
                image1:" ",
                shades:" ",
                price:"₹ 895",
        },
        {
                image:"https://files.myglamm.com/site-images/800x800/open-product-side-bar.jpg",
                title:"POPxo Makeup - Face Kit",
                description:"3-in-1 blush,setting powder, and highlighter palette",
                image1:" ",
                shades:" ",
                price:"₹ 369",
        },
        {
                image:"https://files.myglamm.com/site-images/800x800/Party-parade-(1).jpg",
                title:"Two of Your Kind",
                description:"Long -Lasting Gel Finish Nail Enamel Set",
                image1:"https://www.myglamm.com/images/plus-icon.png",
                shades:"17 SHADES",
                price:"₹ 295",
        },
        {
                image:"https://files.myglamm.com/site-images/800x800/BadRomn-(1).jpg",
                title:"LIT Nail Enamel",
                description:"Chip-resistant,Glossy Nail Enamel",
                image1:"https://www.myglamm.com/images/plus-icon.png",
                shades:"25 SHADES",
                price:"₹ 195",
        },
        {
                image:"https://files.myglamm.com/site-images/800x800/15-Manish-Malhotra-Nail-Lacquer-Post-1-Blush-Babe.jpg",
                title:"Manish Malhotra Gel Finish Nail Lacquer Blush",
                description:"Hi-Shine Gel Finish Nail Enamel",
                image1:"https://www.myglamm.com/images/plus-icon.png",
                shades:"19 SHADES",
                price:"₹ 295",
        },
        {
                image:"https://files.myglamm.com/site-images/800x800/HDBLD-(1).jpg",
                title:"POSE HD Blush Duo",
                description:"HD Soft Focus Blush",
                image1:" ",
                shades:" ",
                price:"₹ 695",
        },
        {
                image:"https://files.myglamm.com/site-images/800x800/staydefined.jpeg",
                title:"Stay Defined",
                description:"2 in 1 Waterproof Matte Eyeliner + HD Brow Powder",
                image1:"https://www.myglamm.com/images/plus-icon.png",
                shades:"1 SHADES",
                price:"₹ 1095",
        },
];
localStorage.setItem("makeupData",JSON.stringify(makeupD));